### ISSUE TITLE
Internal links doesn't work

### ISSUE THREAD

**Issue by LeCuay** [scripthubteam/scripthubteam.github.io#1]
Internal MarkDown links below h3 (###) doesn't work in the website.

For example:

This works
```markdown
[Test](###test1)
```

This doesn't
```markdown
[Test2](####test2)
```

But both of them works on GitHub.

**Comment by MrDevsaider** [comment]
# Forma local de una redirección

Tomaremos de un ejemplo un archivo inexistente llamado: `test.md`

Este mismo archivo contendrá un listado de enlaces ajustado a la manera local:
```
# Contenido de test.md
Este es el contenido de test.md, a continuación un listado de enlaces:
* Indice
  * [Sobre nosotros](#introducción)
```
Desde aquí `[Sobre nosotros](#introducción)` nos llevará al subheader del archivo **Introducción**.

```
# Contenido de test.md
Este es el contenido de test.md, a continuación un listado de enlaces:
* Indice
  * [Sobre nosotros](#introducción)

## Introducción
Hola, haz llegado a la introducción del archivo.
```

# Forma externa de una redirección

Si deseas enlazar a cualquier header de un `.md` externo, debes:
```
# Contenido de test.md
Este es el contenido de test.md, a continuación un listado de enlaces:
* Indice
  * [Enlace externo](https://github.com/scripthubteam/scripthubteam.github.io/blob/master/js/discord-js.md#Instalando-mi-bot)
```
!> **Nota:** No necesariamente se debe añadir los hashes del markdown para identificar headers/subheaders (`#`, `##`, `###`), dentro de la página de la documentación y Github identificará las secciones de los headers con un solo hash, si solo se representa por enlace local/externo.
