### ISSUE TITLE
URL en las guías de discord.js

### ISSUE THREAD

**Issue by wwmoon** [scripthubteam/scripthubteam.github.io#14]
No sé si sea un error o lo hicieron así, pero en las URL's que redireccionan a los artículos de la guía falta un `discord-js`
![image](https://user-images.githubusercontent.com/54691517/68092023-dfd05500-fe97-11e9-85fe-a31824c513b1.png) no como en las demás guías que colocan el nombre de la librería 
![image](https://user-images.githubusercontent.com/54691517/68092031-faa2c980-fe97-11e9-86ed-d46ed940a895.png)

**Comment by wwmoon** [comment]
Acabo de averiguar que pasa lo mismo con la guía de JDA, D.PY y D.RB, en los 3 les falta otro argumento en la URL

**Comment by wwmoon** [comment]
Olvidé comentar que sí está en las "Urls principales", pero de Primeros pasos para delante ya no sale ese distintivo

**Comment by MrDevsaider** [comment]
Pasteo el mensaje acá para ahorrarme más tiempo: 
```
Devsaider
Nah, no es un error
Antes se tenía pensado no abarcar más guías en JS, así que en el directorio de la documentación
la guia de djs está en el root principal de /js/
y no /js/djs/
como /js/eris/
```
